### ISSUE TITLE
Token forking mech

### ISSUE THREAD

**Issue by christopherdancy** [decent-dao/fractal-metafactory#15]
Testing gas cost difference between - snapshots on every token transfer and user snapshot.

on token transfer
<img width="707" alt="image" src="https://user-images.githubusercontent.com/69045872/178484148-92fdfb60-14e8-4211-971f-2d6af4ab2d09.png">

Not on token transfer
<img width="707" alt="image" src="https://user-images.githubusercontent.com/69045872/178484231-007251ba-d283-4ff4-be16-c37b09a6c3e8.png">

**Comment by christopherdancy** [comment]
Decision Log - Taylor and I reviewed the contracts and the snapshot option appears to be the best approach. Each address has their token balance updated on every token transfer (increased gas) - when a token fork occurs, we will snapshot the balances. This new snapshot Id will be used by the claim contract to look up a users allocation and calculate child token allocation.

**Comment by christopherdancy** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/69045872/178509072-ba6ebae0-4552-421e-bc75-54ea92511ecc.png">

**Comment by adamgall** [comment]
@christopherdancy does this issue need to stay open?
